#include<iostream>
using namespace std;
main(){
cout<<"                                                                                                                                  ";<<endl;
cout<<"                                                               OOOOO        OOOOO                                                             ";<<endl;
cout<<"                                                            OOO     OO    OO     OOO                                                      ";<<endl;
cout<<"								 OOO	       O	   OOO				                    ";<<endl;
cout<<"						                OO			    OO				    ";<<endl;
cout<<"							        OO		            OO				    ";<<endl;
cout<<"								OO		            OO				            ";<<endl;
cout<<"								 OOO			  OOO						    ";<<endl;
cout<<"								  OOO			 OOO						    ";<<endl;
cout<<"								     OOO              OOO						    ";<<endl;
cout<<"                               					OO	    OO						    ";<<endl;
cout<<"									   OO	 OO							    ";<<endl;
cout<<"									      OO							    ";<<endl;
cout<<"																            ";<<endl;
cout<<"																	    ";<<endl;
cout<<"																	    ";<<endl;
cout<<"		_________________________________				+											    ";<<endl;
cout<<"		|				|			      +   +							    ";<<endl;
cout<<" 	|				|			    +       +							    ";<<endl;
cout<<"		|				|		          +           +						            ";<<endl;
cout<<"		|				|			+               +		TRIANGLE					    ";<<endl;
cout<<"		|				|		      +                   +							    ";<<endl;
cout<<"		|				|		    +                       +							    ";<<endl;
cout<<"		|				|		                              +							    ";<<endl;
cout<<"		|                               |               +                               +							    ";<<endl;
cout<<"		|				|	      +                                   +							    ";<<endl;
cout<<"		|				|	    +                                       +							    ";<<endl;
cout<<"		|				|	  +                                           +							    ";<<endl;
cout<<"		|				|	+                                               +							    ";<<endl;
cout<<"		|_______________________________|     + + + + + + + + + + + + + + + + + + + + + + + + + + + 			           ";<<endl;
cout<<"                                                                                                                                    ";<<endl;
cout<<"                                                                                                                                    ";<<endl;
cout<<"                   SQUARE                                                                                                                 ";<<endl;
cout<<"                                                                                                                                    ";<<endl;
cout<<"                                                                   .......                                                              ";<<endl;
cout<<"                                                                ...       ...                                                  ";<<endl;
cout<<"                                                             ...             ...                                         ";<<endl;
cout<<"                                        CIRCLE               ..               ..                                  ";<<endl;
cout<<"                                                             ..               ..                                   ";<<endl;
cout<<"                                                             ...             ...                                  ";<<endl;
cout<<"                                                                ...       ...                                                       ";<<endl;
cout<<"                                                                   .......                                                                 ";<<endl;
cout<<"                                                                                                                                 ";<<endl;
cout<<"                                                                                                                                    ";<<endl;
cout<<"                                 \            ___________          ___________              /                                                               ";<<endl;
cout<<"                                  \          |           |        |           |            /                                               ";<<endl;
cout<<"                                   \         |   $$$     |        |    $$$    |           /                                               ";<<endl;
cout<<"                                    \        |___________|        |___________|          /                                                 ";<<endl;
cout<<"                                     \                                                  /                                             ";<<endl;
cout<<"                                      \                                                /                                            ";<<endl;
cout<<"                                       \                     /                        /                                               ";<<endl;
cout<<"                                        \                   /                        /                                                ";<<endl;
cout<<"                                         \                 /  o                     /                                                  ";<<endl;
cout<<"                                          \               /_____                   /                                                      ";<<endl;
cout<<"                                           \                                      /          FACE                                         ";<<endl;
cout<<"                                            \                                    /                                                   ";<<endl;
cout<<"                                             \          _____________           /                                                                  ";<<endl;
cout<<"                                              \         |\/\/\/\/\/\/|         /                                                       ";<<endl;
cout<<"                                               \        |____________|        /                                                       ";<<endl;
cout<<"                                                \                            /                                                        ";<<endl;
cout<<"                                                 \                          /                                                         ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                   HEXAGON                                     ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                      +                              ";<<endl;
cout<<"                                                                                                    +   +                             ";<<endl;
cout<<"                         ____________________________________                                     +       +                                                                 ";<<endl;
cout<<"                        /                                   /                                   +           +                                ";<<endl;
cout<<"                       /                                   /                                  +               +                              ";<<endl;
cout<<"                      /                                   /                                   +               +                                          ";<<endl;
cout<<"                     /                                   /                                    +               +                                        ";<<endl;
cout<<"                    /                                   /                                     +               +                                      ";<<endl;
cout<<"                   /                                   /                                      +               +                                    ";<<endl;
cout<<"                  /                                   /                                         +           +                                  ";<<endl;
cout<<"                 /                                   /                                            +       +                                ";<<endl;
cout<<"                /                                   /          PARALELLOGRAM                        +   +                                     ";<<endl;
cout<<"               /___________________________________/                                                  +                                 ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                                                      ";<<endl;
cout<<"                                                                                                                                      ";
}