#include<iostream>
using namespace std;
main()
{
cout<<"                            ;;;;;;;;;;;                                                      "<<endl;
cout<<"                        ;;;;;         ;;;;;                                          "<<endl;
cout<<"                      ;;;;               ;;;;                                        "<<endl;
cout<<"                     ;;;                   ;;;                                      "<<endl;
cout<<"                     ;;;                   ;;;                                      "<<endl;
cout<<"                     ;;;                   ;;;      CIRCLE                                "<<endl;
cout<<"                     ;;;                   ;;;                                             "<<endl;
cout<<"                      ;;;;               ;;;;                                               "<<endl;
cout<<"                        ;;;;;         ;;;;;                                 "<<endl;
cout<<"                            ;;;;;;;;;;;                                                    "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                     ______________________________                          "<<endl;
cout<<"                     |                            |                              "<<endl;
cout<<"                     |                            |                                "<<endl;
cout<<"                     |                            |                                "<<endl;
cout<<"                     |                            |                               "<<endl;
cout<<"                     |                            |       SQUARE                        "<<endl;
cout<<"                     |                            |                                "<<endl;
cout<<"                     |                            |                                "<<endl;
cout<<"                     |                            |                                "<<endl;
cout<<"                     |                            |                                "<<endl;
cout<<"                     |                            |                                "<<endl;
cout<<"                     |____________________________|                                "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                     ___________________________________                          "<<endl;
cout<<"                    /                                  /                          "<<endl;
cout<<"                   /                                  /                            "<<endl;
cout<<"                  /                                  /                             "<<endl;
cout<<"                 /                                  /                              "<<endl;
cout<<"                /                                  /                               "<<endl;
cout<<"               /                                  /        PARALELLOGRAM           "<<endl;
cout<<"              /                                  /                                 "<<endl;
cout<<"             /                                  /                                  "<<endl;
cout<<"            /                                  /                                   "<<endl;
cout<<"           /__________________________________/                                   "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                    +                                             "<<endl;
cout<<"                                  +   +                                             "<<endl;
cout<<"                                +       +                                             "<<endl;
cout<<"                              +           +                                           "<<endl;
cout<<"                            +               +                                         "<<endl;
cout<<"                            +  +         +  +                                       "<<endl;
cout<<"                            +    +  +  +    +                                       "<<endl;
cout<<"                            +    +     +    +        HEXAGON                        "<<endl;
cout<<"                            +    +     +    +                                                    "<<endl;
cout<<"                            +    +  +  +    +                                                     "<<endl;
cout<<"                            +   +       +  +                                                     "<<endl;
cout<<"                              +           +                                                     "<<endl;
cout<<"                                +       +                                                     "<<endl;
cout<<"                                  +   +                                              "<<endl;
cout<<"                                    +                                             "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                         O                                        "<<endl;
cout<<"                                       O   O                                        "<<endl;
cout<<"                                     O       O                                        "<<endl;
cout<<"                                   O           O          TRIANGLE                             "<<endl;
cout<<"                                 O               O                                        "<<endl;
cout<<"                               O                   O                                       "<<endl;
cout<<"                             O                       O                                                   "<<endl;
cout<<"                           O                           O                         "<<endl;
cout<<"                         O                               O                          "<<endl;
cout<<"                       O                                   O                      "<<endl;
cout<<"                     OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO                    "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                              OOO           OOO                                      "<<endl;
cout<<"                            OOO   OO     OO   OOO                                     "<<endl;
cout<<"                           OO          O          OOO                                "<<endl;
cout<<"                          OO                     OO                                "<<endl;
cout<<"                           OO                   OO                                   "<<endl;
cout<<"                            OO                 OO                                    "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
cout<<"                                                                                 "<<endl;
}
